import { randomUUID } from 'node:crypto';
import { ExecutionEngine, WorkflowEngine, type WorkflowDefinition, type WorkflowExecutionSummary } from '@union/shared';
import { getOperationalDatabase, databaseProvider } from '../db/operational-database.js';
import { workflowRepository } from './workflow-repository.js';
import { realNodeHandler } from './workflow-node-handler.js';
import { env } from '../config/env.js';

const db = getOperationalDatabase();
export class WorkflowJobs {
  static async enqueue(userId: string, workflow: WorkflowDefinition) {
    if (workflow.nodes.length > 50) throw new Error('WORKFLOW_LIMIT: Máximo 50 nós por execução');
    const validation = WorkflowEngine.validate(workflow);
    if (!validation.isValid) throw new Error(validation.errors.map(error => error.message).join(', '));
    const id = randomUUID();
    await db.transaction(async () => {
      await db.lock(`jobs:${userId}`);
      const pending = await db.prepare("SELECT count(*) as total FROM workflow_jobs WHERE user_id = ? AND status IN ('QUEUED', 'RUNNING')").get(userId);
      if (pending.total >= 3) throw new Error('WORKFLOW_QUOTA: Máximo 3 execuções pendentes');
      await db.prepare('INSERT INTO workflow_jobs (id, user_id, workflow_json, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)').run(id, userId, JSON.stringify(workflow), 'QUEUED', Date.now(), Date.now());
    })();
    return { id, status: 'QUEUED' };
  }
  static async get(id: string, userId: string) {
    const job = await db.prepare('SELECT * FROM workflow_jobs WHERE id = ? AND user_id = ?').get(id, userId);
    if (!job) return null;
    return { id: job.id, status: job.status, error: job.error, result: job.result_json ? JSON.parse(job.result_json) : undefined };
  }
  static async cancel(id: string, userId: string) {
    return (await db.prepare("UPDATE workflow_jobs SET status = 'STOPPED', updated_at = ? WHERE id = ? AND user_id = ? AND status IN ('QUEUED', 'RUNNING')").run(Date.now(), id, userId)).changes > 0;
  }
  static async runNext(): Promise<boolean> {
    const job = await db.transaction(async () => {
      // A dead worker never silently retries provider calls (could double bill).
      // Lease expiration records a recoverable failure; operator/user can retry.
      await db.prepare("UPDATE workflow_jobs SET status = 'FAILED', error = 'WORKER_LEASE_EXPIRED: Reveja os nós concluídos antes de repetir', updated_at = ? WHERE status = 'RUNNING' AND updated_at < ?").run(Date.now(), Date.now() - 90000);
      const suffix = databaseProvider() === 'postgres' ? ' FOR UPDATE SKIP LOCKED' : '';
      const found = await db.prepare(`SELECT * FROM workflow_jobs WHERE status = 'QUEUED' ORDER BY created_at LIMIT 1${suffix}`).get();
      if (!found) return null;
      await db.prepare("UPDATE workflow_jobs SET status = 'RUNNING', updated_at = ? WHERE id = ? AND status = 'QUEUED'").run(Date.now(), found.id);
      return found;
    })();
    if (!job) return false;
    const controller = new AbortController();
    const timer = setInterval(() => {
      void db.prepare('SELECT status FROM workflow_jobs WHERE id = ?').get(job.id).then(async row => {
        if (row?.status !== 'RUNNING') controller.abort();
        else await db.prepare('UPDATE workflow_jobs SET updated_at = ? WHERE id = ?').run(Date.now(), job.id);
      }).catch(() => controller.abort());
    }, 10000);
    timer.unref();
    const timeout = setTimeout(() => controller.abort(), 15 * 60 * 1000);
    timeout.unref();
    try {
      const workflow: WorkflowDefinition = JSON.parse(job.workflow_json);
      const events: unknown[] = [];
      let checkpoint: Promise<unknown> = Promise.resolve();
      const summary = await ExecutionEngine.execute({ workflow, plan: WorkflowEngine.generateExecutionPlan(workflow, 'RUN'), signal: controller.signal,
        handler: realNodeHandler(job.user_id), onNodeEvent: event => { events.push(event); if (event.type === 'NODE_COMPLETED' || event.type === 'NODE_FAILED') checkpoint = checkpoint.then(() => db.prepare("UPDATE workflow_jobs SET result_json = ?, updated_at = ? WHERE id = ? AND status = 'RUNNING'").run(JSON.stringify({ events }), Date.now(), job.id)); } });
      await checkpoint;
      // Saved workflow history is always generated by the server, never by a posted cost.
      if (await workflowRepository.getWorkflow(workflow.id, job.user_id)) await workflowRepository.recordWorkflowRun(job.user_id, workflow.id, {
        status: summary.status === 'IDLE' ? 'FAILED' : summary.status, totalNodes: summary.totalNodes,
        completedNodes: summary.completedNodes, failedNodes: summary.failedNodes, totalTokens: summary.totalTokens,
        totalCostCredits: summary.totalCostCredits, durationMs: summary.durationMs, summary: summary as unknown as Record<string, unknown> });
      await db.prepare("UPDATE workflow_jobs SET status = ?, result_json = ?, updated_at = ? WHERE id = ? AND status = 'RUNNING'").run(summary.status, JSON.stringify({ summary, events }), Date.now(), job.id);
    } catch (error) {
      await db.prepare("UPDATE workflow_jobs SET status = 'FAILED', error = ?, updated_at = ? WHERE id = ? AND status = 'RUNNING'").run(error instanceof Error ? error.message : 'WORKFLOW_FAILED', Date.now(), job.id);
    } finally { clearInterval(timer); clearTimeout(timeout); }
    return true;
  }
}
